Integration with Travis and coveralls
ywangii/await-targz pull request #1
Opened 2018-05-16 23:42 UTC by ywangii

2018-05-16 23:47 UTC, jcrugzz requested changes

2018-05-16 23:47 UTC, jcrugzz commented on .travis.yml
> +node_js:
remove 9, add 10

2018-05-16 23:47 UTC, gergelyke approved these changes

2018-05-16 23:47 UTC, gergelyke commented on .travis.yml
> +  - "8"
can you add 10?

2018-05-16 23:53 UTC, ywangii commented on .travis.yml
> +node_js:
yes, TIL, copy/paste is bad. XD

2018-05-16 23:53 UTC, ywangii commented on .travis.yml
> +  - "8"
updated! thanks for quick review sir!

2018-05-17 00:06 UTC, jcrugzz approved these changes

2018-05-17 04:38 UTC, merged